CREATE TABLE public.menu_ingredients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    menu_item_id BIGINT NOT NULL,
    ingredient_id BIGINT NOT NULL,
    quantity NUMERIC(10, 2) NOT NULL,
    unit TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),

    CONSTRAINT fk_menu_item
        FOREIGN KEY(menu_item_id) 
        REFERENCES public.menu_items(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_ingredient
        FOREIGN KEY(ingredient_id) 
        REFERENCES public.ingredients(id)
        ON DELETE CASCADE
);

-- RLS Policies
ALTER TABLE public.menu_ingredients ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow read access to all users" 
ON public.menu_ingredients
FOR SELECT 
USING (true);

CREATE POLICY "Allow insert access to authenticated users" 
ON public.menu_ingredients
FOR INSERT 
WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Allow update access to authenticated users" 
ON public.menu_ingredients
FOR UPDATE
USING (auth.role() = 'authenticated')
WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Allow delete access to authenticated users"
ON public.menu_ingredients
FOR DELETE
USING (auth.role() = 'authenticated');

-- Comments
COMMENT ON TABLE "public"."menu_ingredients" IS 'Join table to link menu items with their ingredients.';
COMMENT ON COLUMN "public"."menu_ingredients"."quantity" IS 'Amount of the ingredient required for the menu item.';
COMMENT ON COLUMN "public"."menu_ingredients"."unit" IS 'Unit of measurement for the quantity (e.g., grams, oz, pcs).'; 