// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rewwtmqnxzqmqoqpplxf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJld3d0bXFueHpxbXFvcXBwbHhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0NzA1ODUsImV4cCI6MjA2NTA0NjU4NX0.-mZmjFcCWtMr7LzXsdGcNQwNr6bdUWxmfyMWd2K--SU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);